# Generated by Django 5.2.4 on 2025-07-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='filial',
        ),
        migrations.DeleteModel(
            name='Filial',
        ),
    ]
