# Generated by Django 5.2.5 on 2025-11-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passport_serial',
        ),
    ]
