# Generated by Django 4.2.27 on 2025-12-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_filial_user_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('new', 'Yangi'), ('creditor', 'Kreditor'), ('accountant', 'Buxgalter')], default='new', max_length=20),
        ),
    ]
