# Generated by Django 4.2.27 on 2026-01-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='manager',
            field=models.CharField(default='', max_length=50),
        ),
    ]
