# Generated by Django 4.2.27 on 2026-01-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_filial_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('new', 'Yangi'), ('creditor', 'Kreditor'), ('accountant', 'Buxgalter'), ('admin', 'Admin')], default='new', max_length=20),
        ),
    ]
