# Generated by Django 6.0.1 on 2026-01-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_company_filial_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='accountant',
            field=models.CharField(default='', max_length=50),
        ),
    ]
