# Generated by Django 4.2.27 on 2026-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filial',
            name='accountant',
        ),
        migrations.RemoveField(
            model_name='filial',
            name='manager',
        ),
        migrations.AddField(
            model_name='filial',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
