# Generated by Django 6.0.1 on 2026-01-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0003_order_uuid_product_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('kilo', 'kilo'), ('dona', 'dona'), ('litr', 'litr')], default='dona', max_length=50),
        ),
    ]
