# Generated by Django 6.0.1 on 2026-01-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0004_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='p_type',
        ),
    ]
