# Generated by Django 6.0.1 on 2026-01-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0005_rename_type_product_p_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_type',
            field=models.CharField(choices=[('kilo', 'kilo'), ('dona', 'dona'), ('litr', 'litr'), ('metr', 'metr')], default='dona', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
