# Generated by Django 6.0.1 on 2026-01-22 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0009_alter_orderitem_filial'),
        ('users', '0017_remove_filial_accountant_remove_filial_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.filial'),
        ),
    ]
