# Generated by Django 6.0.1 on 2026-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0010_alter_order_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
