# Generated by Django 6.0.1 on 2026-01-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0011_order_sold_price_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interest',
            field=models.IntegerField(default=0),
        ),
    ]
