# Generated by Django 6.0.1 on 2026-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0012_product_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='income',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
