# Generated by Django 6.0.1 on 2026-01-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0014_orderitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('act_type', models.CharField(choices=[('kirim', 'kirim'), ('chiqim', 'chiqim'), ('null', 'null')], default='null')),
            ],
        ),
    ]
