# Generated by Django 6.0.1 on 2026-02-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0015_action'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Action',
        ),
    ]
