# Generated by Django 6.0.1 on 2026-02-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0016_delete_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='income',
            new_name='in_price',
        ),
    ]
