# Generated by Django 6.0.2 on 2026-02-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0018_alter_order_created_at_alter_orderitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sotilgan', 'sotilgan'), ('qaytarilgan', 'qaytarilgan')], default='sotildi', max_length=20),
        ),
    ]
