# Generated by Django 6.0.2 on 2026-02-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisa', '0019_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('sotilgan', 'sotilgan'), ('qaytarilgan', 'qaytarilgan')], default='sotilgan', max_length=20),
        ),
    ]
